name: 271-52签到

on:
  #push: # push触发
  #  branches: [ main ]
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
#    - cron: '*/30 20-23,0-16 * * *' # cron表达式，Actions时区是UTC时间，所以要往前推8个小时(4-23)
    - cron: '05 01 * * *'

jobs:
  daily-task:
    if: github.event.repository.owner.id == github.event.sender.id

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]
        node-registry: ['https://registry.npmjs.org']

    steps:
    
    # 检出
    - name: Checkout
      uses: actions/checkout@v2
      
    # 设置服务器时区为东八区 
    - name: Timezone CST +8
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: ${{ matrix.node-registry }}

    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
    - name: restore npm cache
      uses: actions/cache@v2
      id: use-npm-cache
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: restore npm dependencies
      uses: actions/cache@v2
      id: use-npm-depends
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-depends-${{ hashFiles('**/package-lock.json') }}

    - name: restore task cache
      uses: actions/cache@v2
      id: use-task-cache
      with:
        path: |
          /home/runner/.AutoSignMachine
        key: ${{ runner.os }}-task-${{ steps.get-date.outputs.date }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.use-npm-cache.outputs.cache-hit != 'true' || steps.use-npm-depends.outputs.cache-hit != 'true'
      run: npm install

    # 运行 unicom 签到任务
    - name: Run unicom daily task
      env:
        iqiyi1_P00001: ${{secrets.iqiyi1_P00001}}
        iqiyi1_P00PRU: ${{secrets.iqiyi1_P00PRU}}
        iqiyi1_QC005: ${{secrets.iqiyi1_QC005}}
        iqiyi1_dfp: ${{secrets.iqiyi1_dfp}}
        iqiyi2_P00001: ${{secrets.iqiyi2_P00001}}
        iqiyi2_P00PRU: ${{secrets.iqiyi2_P00PRU}}
        iqiyi2_QC005: ${{secrets.iqiyi2_QC005}}
        iqiyi2_dfp: ${{secrets.iqiyi2_dfp}}
        52_htVD_2132_auth: ${{secrets.52_htVD_2132_auth}}
        52_htVD_2132_saltkey: ${{secrets.52_htVD_2132_saltkey}}
        notify_sctkey: ${{secrets.NOTIFY_SCKEY}}
      run: node index.js iqiyi --P00001=${iqiyi1_P00001} --P00PRU=${iqiyi1_P00PRU} --QC005=${iqiyi1_QC005} --dfp=${iqiyi1_dfp} ;
           node index.js iqiyi --P00001=${iqiyi2_P00001} --P00PRU=${iqiyi2_P00PRU} --QC005=${iqiyi2_QC005} --dfp=${iqiyi2_dfp} ;
           node index.js 52pojie --htVD_2132_auth=${52_htVD_2132_auth} --htVD_2132_saltkey=${52_htVD_2132_saltkey}
